### ISSUE TITLE
Error: Deno + TypeScript + Preact

### ISSUE THREAD

**Issue by castrogarciajs** [bluwy/create-vite-extra#37] opened 2023-10-20 19:05 UTC
Hello team, 

I decided to try a preact template with typescript and deno, but when I run the project with the command `deno task dev` I get a package error... Apparently it has to do with babel.

## logs
```sh
Cannot find package '@babel/plugin-transform-react-jsx-development'
```

## more info
![2023-10-20 (2)](https://github.com/bluwy/create-vite-extra/assets/116913262/a4042441-5c1c-4710-8961-fcce751dd401)

**Comment by bluwy** [comment] 2023-10-21 10:44
Duplicate of #34

**Closed by bluwy** 2023-10-21 10:44 UTC
