### ISSUE TITLE
`deno-react-ts` hangs and shows blank page when start server

### ISSUE THREAD

**Issue by char8x** [bluwy/create-vite-extra#21] opened 2022-12-19 11:36 UTC
### Reproduce Step

```sh
deno run -A npm:create-vite-extra --template deno-react-ts
# Project name: example
cd example
deno task dev
```

### Result

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/6831013/208417358-7a376a11-c265-4054-a127-89915be41729.png">

### Environment

macOS 12.6.2 arm64
deno 1.29.1

**Comment by bluwy** [comment] 2022-12-19 14:00
I can reproduce this for all Deno React templates too, including the JS version and SWC variants. Looks like the websocket server hangs somehow. Strangely it seems to work for the Preact and Solid templates.

I was able to run it fine with Deno 1.28.1. The issue is reproducible since 1.29.1 for me. (didn't test 1.29.0)

cc @bartlomieju

**Comment by bartlomieju** [comment] 2022-12-20 23:01
Thanks for the report, we are aware of the problems, they are caused by our HTTP server implementation that we are currently reworking. Let's keep this issue open for now, I will let you know when we release updated version with new server.

**Comment by bluwy** [comment] 2023-07-04 07:53
Closing as the upstream issue has been fixed.

**Closed by bluwy** 2023-07-04 07:53 UTC
Labels: framework: deno
