### ISSUE TITLE
type errors with `deno-react` + `Typescript`

### ISSUE THREAD

**Issue by scarf005** [bluwy/create-vite-extra#32] opened 2023-05-10 05:11 UTC
## Issue

![image](https://github.com/bluwy/create-vite-extra/assets/54838975/d3f07967-c420-4aaa-b78f-cfe8c87f75df)
`JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.` errors are popping OOTB.

this may be related to https://github.com/denoland/deno/issues/9425.

## How to reproduce

1. follow the installation steps.
```sh
$ deno run --allow-read --allow-write --allow-env npm:create-vite-extra@latest
✔ Project name: … vite-project
✔ Select a template: › deno-react
✔ Select a variant: › TypeScript

Scaffolding project in /home/scarf/repo/cata/vite-project...

Done. Now run:

  cd vite-project
  deno task dev
```

2. enable deno for the workspace.
![image](https://github.com/bluwy/create-vite-extra/assets/54838975/52b3ddb0-205b-455d-ad3c-374369cfff33)

## System Information

ubuntu 23.04
vscode 1.78.1, with deno extension v3.17.0

**Comment by bluwy** [comment] 2023-05-12 07:28
There's also a similar issue open in Vite recently without Deno: https://github.com/vitejs/vite/issues/13129. Not sure if it's related. There's also this Deno issue which seems to be the same: https://github.com/denoland/deno/issues/16653. The solution (https://github.com/denoland/deno/issues/16653#issuecomment-1383657630) worked a bit but there's still lingering TS errors.

cc @bartlomieju

**Comment by rpasechnikov** [comment] 2023-05-12 09:52
Hi! 

That sounds similar to an issue I had a few days ago. Updating `moduleResolution` to `node` (maybe others too) fixed it for me. Updating VS Code was ultimately the solution, which allowed me to roll back changes to `moduleResolution` back to `bundler`.

https://github.com/vitejs/vite/issues/13129

**Comment by bartlomieju** [comment] 2023-05-12 11:42
Thanks for the ping, I'll try to investigate this problem.

**Comment by hastebrot** [comment] 2023-07-13 13:59
as a work-around I've disabled the path to my vite application (running on deno runtime) for `deno.enablePaths` in `.vscode/settings.json`.

I've created a `deno-react` application using `npm:create-vite-extra`
```ts
❯ deno run --allow-read --allow-write --allow-env npm:create-vite-extra@latest
```

After I renamed `src/main.jsx` to `src/main.tsx` I had to change `vite.config.mjs` to include `npm:@types/react`
```ts
import "npm:react@18.2.0";
import "npm:react-dom@18.2.0";
import "npm:react-router-dom@6.14.1";

try {
  await import("npm:@types/react");
  await import("npm:@types/react-dom");
} catch (ignore) {}
```

the imports need to be wrapped into a `try-catch` because vite/deno complain about import problems, but the important thing is that `./node_modules/@types/react` exists for the normal vscode typescript LSP.

**Comment by baosoy** [comment] 2024-04-08 10:43
You can just add the following to `deno.json` too, this works for me:

```
  "imports": {
    "react": "npm:react",
    "react/": "npm:react/"
  },
  "compilerOptions": {
    "jsx": "react-jsx"
  }
```

**Comment by RioChndr** [comment] 2024-08-18 09:02
I had same problem, the problem is we had to include the types of react into deno runtime, I write the solution on [my blog](https://riochndr.com/posts/running-vite-react-typescript-with-deno/). tldr; I use esm.sh instead npm.

**Comment by fushihara** [comment] 2024-08-20 23:50
@RioChndr 
https://riochndr.com/posts/running-vite-react-typescript-with-deno/screenshot-vs-code-success.png
I read the article. It is very informative.

The last image in the article also shows an svg import error, can this be fixed?

**Comment by RioChndr** [comment] 2024-08-26 12:17
Hi @fushihara. I'm sorry I can't fix that, also I found other problem that vite error when we import other module into deno-typescript file, it will error if we import
- `import x from "https://jsr.io/xyz"
- `import x from "npm:xyz"
- `import x from "xyz"`, package `xyz` mapped at `deno.json`.

I can't find the solution for this.

**Comment by AmanNegi** [comment] 2024-09-23 17:46
> The last image in the article also shows an svg import error, can this be fixed?

@fushihara You can fix it by adding the below in your `deno.json`:

```json
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "https://esm.sh/react@18.2.0"
  }
```

**Comment by bluwy** [comment] 2024-10-14 10:34
I've updated the deno templates in v2.3.0 that now uses `"imports"` and `"compilerOptions"` that should work better in the IDE now. Locally I'm no longer getting any type errors as long as you have the Deno VSCode extension installed.

Let me know if this works for y'all and if there's no issues I'll close this as fixed.

---

There's one caveat I found is that I have to do this:

https://github.com/bluwy/create-vite-extra/blob/e5a7749b84f396ee7494339aa9e9db42fc67577f/template-deno-preact-ts/src/app.tsx#L2-L3

Ambient types from `src/vite-env.d.ts` don't seem to work. I tried:

1. Inline the raw `declare module '.svg'` declaration to file.
2. Inline the `/// <reference types="vite/client" />` to the top of the file.
3. Use `compilerOptions.types: ['vite/client']` in `deno.json`

But all still errors out for me. Based on https://docs.deno.com/runtime/reference/ts_config_migration/#using-ambient-or-global-types, seems like it should work. It works with the base Vite template and Deno node compat, as without a `deno.json`, it uses the `tsconfig.json` and works correctly. But from what I can tell, the norm is to put it in `deno.json` instead.

 Perhaps @bartlomieju or @marvinhagemeister can help out here?

**Comment by AmanNegi** [comment] 2024-10-14 12:27
Everything works fine now! I also face no intellisense errors. 

To me what I found really counter-intuitive are the `@deno-types` annotation. Do we have to do add it manually for each type import we add to `deno.json`? It would be great if it could be inferred similar to how types works with node.

**Comment by bluwy** [comment] 2024-10-14 12:33
I find that part a bit odd too. I followed the docs here https://docs.deno.com/runtime/fundamentals/node/#importing-types to set it up since I couldn't get it to auto-pick-up the types from `@types/*`. I'm not sure if it's an intentional feature.

**Comment by bluwy** [comment] 2024-10-21 08:17
Going to close this for now as I believe the new Deno templates should fix the originally reported issue. However my notes from https://github.com/bluwy/create-vite-extra/issues/32#issuecomment-2410778280 still stand if anyone knows more about this to polish the templates up further.

**Closed by bluwy** 2024-10-21 08:17 UTC
Labels: framework: deno
